- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false # user can see what they are entering in the prompt
  - name: PASSWORD
    prompt: please enter your password
    private: true
  tasks:
  - name: Printing the values from prompt
    ansible.builtin.debug:
      msg: "username is: {{USERNAME}}, password is {{PASSWORD}}"