- name: variables from play level
  hosts: localhost
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: PERSON
  #   prompt: please enter your wishes
  #   private: false # user can see what they are entering in the prompt
  # - name: WISHES
  #   prompt: please enter your wishes
  #   private: true
  vars:
    PERSON: "Gopi from play"
    WISHES: "Morning from play"
  tasks:
  - name: check variables
    # vars:
    #   PERSON: "Gopi from task"
    #   WISHES: "Morning from task"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

#CMD Level
#TASK Level
#FILE Level
#Prompt Level
#CMD Level
#CMD Level