- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.command:
    register: user # user is a variable name

  - name: print variable values
    ansible.builtin.debug:
     msg: "USER op is: {{user}}