- name: loops
  hosts: localhost
  become: yes
  tasks:
  # - name: printing the installed packages
  #   ansible.builtin.package:
  #     name: "{{item}}"   # Item is a default keyword
  #     state: present 
  #   loop:
  #   - git
  #   - mysql
  #   - postfix
  #   - mongodb
  - name: install or uninstall packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - {name: 'git', state: 'absent'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'yum', state: 'present'}
    - {name: 'nginx', state: 'present'}